---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    driver: kvm
    options:
      memory: 2048
      cpus: 2
# lint:
#   name: yamllint
platforms:
  - name: instance
    box: ${MOLECULE_DISTRO_BOX:-"generic/ubuntu2004"}
    config_options:
        ssh.keep_alive: yes
        ssh.remote_user: 'vagrant'
        synced_folder: true
provisioner:
  name: ansible
  log: true
  inventory:
    links:
      host_vars: host_vars/
  # lint:
  #   name: ansible-lint
verifier:
  name: testinfra
  # lint:
  #   name: flake8
